version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ./../:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm