controllers:
    resource: ../src/Shared/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: annotation

gesdinet_jwt_refresh_token:
    path: /api/auth/token/refresh

api_login_check:
    path: /api/auth/token/login

users:
    resource: ../src/Users/Infrastructure/Controller/
    type: annotation